"""DYST (did you see that? 👀) — one-shot build script.

Builds the project with PyInstaller (DYST.spec), then copies config.json and
the media/ folder into the build output so the .exe has everything it needs
next to it (external, user-editable config + media — no bundling).

Usage:
    .venv\Scripts\python build.py            # full build + copy
    python build.py --skip-copy                # build only

Exits 0 on success, nonzero on failure.
"""

from __future__ import annotations

import argparse
import os
import shutil
import subprocess
import sys
from pathlib import Path

TEST_EXCLUDE = {
    # test marker files
    "test_scare.mp4", "test_scare.png", "test_green.png", "test_scare.json",
}

ROOT = Path(__file__).resolve().parent
SPEC = ROOT / "DYST.spec"
DIST_DIR = ROOT / "dist" / "DYST"          # PyInstaller onedir output
CONFIG_SRC = ROOT / "config.json"
CONFIG_TEMPLATE = ROOT / "config_template.json"
MEDIA_SRC = ROOT / "media"
COPY_ITEMS = ("config.json", "config_template.json", "media")
ICON_SRC = ROOT / "icon.webp"
ICON_DST = ROOT / "icon.ico"


def _build_icon() -> bool:
    """Convert icon.webp -> icon.ico (multi-size) for the EXE.

    Windows .exe icons must be .ico; we generate it at build time from
    icon.webp so the source asset stays a single image. Drops to a
    warning if Pillow is missing (icon then stays off).
    """
    if not ICON_SRC.is_file():
        print("[build] no icon.webp found — building without icon")
        return True
    try:
        from PIL import Image
    except ImportError:
        print("[build] WARNING: Pillow missing — building without icon",
              file=sys.stderr)
        return False
    try:
        img = Image.open(ICON_SRC)
        if img.mode not in ("RGBA", "RGB", "P"):
            img = img.convert("RGBA")
        img.save(ICON_DST, format="ICO",
                 sizes=[(16, 16), (32, 32), (48, 48), (256, 256)])
        print(f"[build] icon: {ICON_SRC} -> {ICON_DST}")
    except OSError as exc:
        print(f"[build] WARNING: failed to build icon.ico: {exc}",
              file=sys.stderr)
        return False
    # Embed the tray icon into the Python package so the tray can load it
    # at runtime without needing icon.ico/icon.webp next to the exe.
    try:
        import base64
        data = base64.b64encode(ICON_DST.read_bytes()).decode("ascii")
        target = ROOT / "dyst" / "_embedded_icon.py"
        target.write_text(f"# Auto-generated by build.py — do not edit.\nICON_BASE64 = {repr(data)}\n", encoding="utf-8")
        print(f"[build] embedded icon -> {target}")
    except Exception as exc:
        print(f"[build] WARNING: failed to embed icon: {exc}", file=sys.stderr)
    return True


def _run_build() -> int:
    print(f"[build] PyInstaller: {sys.executable} -m PyInstaller {SPEC.name}")
    proc = subprocess.run(
        [sys.executable, "-m", "PyInstaller", str(SPEC), "--noconfirm", "--clean"],
        cwd=str(ROOT),
    )
    if proc.returncode != 0:
        print(f"[build] FAILED (PyInstaller exit code {proc.returncode})", file=sys.stderr)
        return proc.returncode
    if not (DIST_DIR / "DYST.exe").is_file():
        print(f"[build] FAILED: output exe not found at {DIST_DIR / 'DYST.exe'}", file=sys.stderr)
        return 1
    print(f"[build] PyInstaller OK -> {DIST_DIR}")
    return 0


def _copytree_filtered(src: Path, dst: Path) -> None:
    """Copy src tree to dst, skipping test assets."""
    for root, dirs, files in os.walk(src):
        rel_root = Path(root).relative_to(src)
        target_dir = dst / rel_root
        target_dir.mkdir(parents=True, exist_ok=True)
        for fname in files:
            if fname in TEST_EXCLUDE:
                print(f"[copy] skipping test asset: {rel_root / fname}")
                continue
            shutil.copy2(Path(root) / fname, target_dir / fname)


def _copy_runtime_files() -> int:
    """Refresh config.json and media/ inside the build output (fresh copy)."""
    for name in COPY_ITEMS:
        src = ROOT / name

        # Remove the previous copy so stale files don't linger (source of truth
        # is always the project root).
        dst = DIST_DIR / name
        try:
            if dst.exists():
                if dst.is_dir():
                    shutil.rmtree(dst)
                else:
                    dst.unlink()

            if not src.exists():
                print(f"[copy] WARNING: {src} does not exist — skipping")
                continue

            if src.is_dir():
                # Copy media tree while skipping test assets
                if name == "media":
                    _copytree_filtered(src, dst)
                else:
                    shutil.copytree(src, dst)
            else:
                shutil.copy2(src, dst)
            print(f"[copy] {name} -> {DIST_DIR / name}")
        except OSError as exc:
            print(f"[copy] FAILED copying {name}: {exc}", file=sys.stderr)
            return 1
    return 0


def _run_build() -> int:
    print(f"[build] PyInstaller: {sys.executable} -m PyInstaller {SPEC.name}")
    proc = subprocess.run(
        [sys.executable, "-m", "PyInstaller", str(SPEC), "--noconfirm", "--clean"],
        cwd=str(ROOT),
    )
    if proc.returncode != 0:
        print(f"[build] FAILED (PyInstaller exit code {proc.returncode})", file=sys.stderr)
        return proc.returncode
    if not (DIST_DIR / "DYST.exe").is_file():
        print(f"[build] FAILED: output exe not found at {DIST_DIR / 'DYST.exe'}", file=sys.stderr)
        return 1
    print(f"[build] PyInstaller OK -> {DIST_DIR}")
    return 0


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(prog="build", description="Build DYST and stage runtime files.")
    parser.add_argument("--skip-copy", action="store_true", help="build only; don't copy config/media")
    args = parser.parse_args(argv)

    if not SPEC.is_file():
        print(f"[build] ERROR: spec not found: {SPEC}", file=sys.stderr)
        return 1

    _build_icon()  # non-fatal; warns on failure, builds without icon

    rc = _run_build()
    if rc != 0:
        return rc

    if not args.skip_copy:
        rc = _copy_runtime_files()
        if rc != 0:
            return rc
    else:
        print("[build] --skip-copy: config/media not copied")

    total = sum(
        f.stat().st_size
        for f in DIST_DIR.rglob("*")
        if f.is_file()
    )
    print(f"[build] done — {DIST_DIR} ({total / 1048576:.1f} MB), exe: {DIST_DIR / 'DYST.exe'}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())